apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  MONGODB_URI: "${MONGODB_URI}"
  DB_NAME: "${DB_NAME}"
  API_AUTH_TOKEN: "${API_AUTH_TOKEN}"
