# apiVersion: v1
# kind: Service
# metadata:
#   name: todo-app-public
#   namespace: todo-app
# spec:
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#     - "<YOUR_IP>/32"
#   selector:
#     app: todo-app
#   ports:
#     - port: 80 
#       targetPort: 8000
#       protocol: TCP
