name: CI-CD

on: [push]

jobs:
  test:
    name: build & test
    environment: demo
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s --health-timeout=5s --health-retries=12

    env:
      MONGODB_URI: mongodb://127.0.0.1:27017/todo_test
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v5

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci

      # (optional) extra wait in case healthcheck cmd isn't available
      - name: Wait for Mongo
        shell: bash
        run: |
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/27017) >/dev/null 2>&1 && break
            sleep 1
          done

      - name: Run tests
        run: npm test -- --runInBand
