name: CI-CD

on: [push]

jobs:
  test:
    name: build & test
    environment: demo
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s --health-timeout=5s --health-retries=12

    env:
      MONGODB_URI: mongodb://127.0.0.1:27017/todo_test
      NODE_ENV: test
      API_KEY: ${{ secrets.API_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci

      # (optional) extra wait in case healthcheck cmd isn't available
      - name: Wait for Mongo
        shell: bash
        run: |
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/27017) >/dev/null 2>&1 && break
            sleep 1
          done

      - name: Run tests
        run: npm test -- --runInBand


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ahmedezz9/todo-app

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

